name = "TransportTestbed"
uuid = "6614d925-a3dc-4425-840b-44859a9bca1b"
authors = ["Daniel Sharp <dannys4@mit.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
